metadata:
    name: pyBurnBuild
    version: 0.1.0
    description: build system written in python for projects in C, C++, Python, ASM
    language: python

compiler:
    name: gcc
    base_compiler_flags:
        - "-c"
    linker_flags:
        - "-03"
